### PR TITLE
Add initial opensuse support

### LINKED ISSUE #1698: Add support for opensuse?
Currently beaker-hostgenerator supports opensuse well. but beaker-rspec not.

If opensuse15-64 is selected as platform, I got an error

>   Unsupported platform name opensuse-15-x86_64

https://www.travis-ci.com/github/jkroepke/puppet-module-autofs/jobs/502897451

Since RedHat decide deprecate CentOS in favor of CentOS Stream, OpenSuse gets more interests.

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #1698

### CODE REVIEW

**Comment by jkroepke** [comment]
I just looks for SLES and add OpenSuse, expect for rpm names.

I don't know, how I could do integration tests. It's known if this module is working on OpenSuse 15 (or SLES 15)

**Comment by trevor-vaughan** [comment]
I don't see any issue adding this since it's mostly syntactic sugar but OpenSUSE has worked for quite some time https://github.com/simp/pupmod-simp-rsync/blob/master/spec/acceptance/nodesets/suse.yml

**Comment by bastelfreak** [comment]
@jkroepke thanks for the PR, can you please take a look at the merge conflict?

**Comment by jkroepke** [comment]
Done 👍

**Review by bastelfreak — APPROVED** [review]

**Comment by jkroepke** [comment]
If possible, please merge soon. I'll not constantly resolve merge conflicts.

**Pull request merged**
